theme: jekyll-theme-cayman
title: Budgeted Reinforcement Learning in Continuous State Space
description: Nicolas Carrara*, Edouard Leurent*, Romain Laroche, Tanguy Urvoy, Odalric-Ambrym Maillard, Olivier Pietquin

github:
  repository_url: http://github.com/eleurent/rl-agents
  paper_url: https://arxiv.org/abs/1903.01004
